### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by jsevereyn** [cboursnell/crb-blast#16]
I have tried different ways to install it, playing with the ruby ​​and blast versions and it doesn't work for me.
I always get the same error message:
`(crb-blast) coralpardo@Corals-MacBook-Pro ~ % crb-blast         
/Users/coralpardo/miniconda3/envs/crb-blast/share/rubygems/bin/crb-blast: line 6: /Users/coralpardo/miniconda3/envs/crb-blast/share/rubygems/bin/ruby: No such file or directory
/Users/coralpardo/miniconda3/envs/crb-blast/share/rubygems/bin/crb-blast: line 6: exec: /Users/coralpardo/miniconda3/envs/crb-blast/share/rubygems/bin/ruby: cannot execute: No such file or directory`

install it through conda:
conda create --name crb-blast

conda activate crb-blast

conda install -c bioconda blast

conda install -c conda-forge ruby

gem install crb-blast

Is there a change regarding the readme instructions or something that Im missing?

**Comment by blahah** [comment]
I think the problem is that you're running ruby through conda, which appears to report its ruby binary location differently. I'd recommend just using `rvm` (https://rvm.io) to install ruby, then installing `crb-blast` using `gem install crb-blast`.

**Comment by jsevereyn** [comment]
Yes, thanks, I noticed tat later, it was really a very simple fix, sorry

**Comment by blahah** [comment]
@jsevereyn I don't have permissions to close the issue, would you mind closing it if the problem is resolved for you?

**Comment by jsevereyn** [comment]
of course, thanks
